Adds editing README.md and pushing changes to workflow

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -7,7 +7,7 @@ name: CI
 on:
   schedule:
     # * is a special character in YAML so you have to quote this string
-    - cron:  '*/15 * * * *'
+    - cron:  '*/5 * * * *'
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -23,10 +23,11 @@ jobs:
 
     # Runs a single command using the runners shell
     - name: Run a one-line script
-      run: echo Hello, world!
+      run: echo Hello, world! >> README.md
 
     # Runs a set of commands using the runners shell
-    #- name: Run a multi-line script
-     # run: |
-      #  echo Add other actions to build,
-       # echo test, and deploy your project.
+    - name: Run a multi-line script
+      run: |
+        git commit README.md -m 'Update README.md with test Cron job' || echo "Update README.md failed"
+        git push origin || echo "Push Failed"
+
